### ISSUE TITLE
Redot engine website needs to add additional paths to fix documentation links

### ISSUE THREAD

**Issue by tokengamedev** [Redot-Engine/redot-landing-page#138]
**Issue description:**
Following links are missing or needs to be created:
https://redotengine.org/license (\about\faq.rst, about/complying_with_licenses.rst)
https://redotengine.org/community (\introduction\community.rst)
https://redotengine.org/contact (\about\faq.rst)

Either pages have to be created or documentation has to be updated

**Comment by opdev1004** [comment]
looks like it belongs to document website

**Comment by chrisrabe** [comment]
Agreed. I don't think we define those links anywhere in the site. I'm not sure what we'll even put there. Must be one of those dead links that's lingering around in the docs because the docs is a fork of Godot docs.

Please raise an issue here:
https://github.com/Redot-Engine/redot-docs

The docs just need to be updated so that their license link goes to the Redot engine license and community and contact just redirects to the Redot engine landing page

**Comment by charlottewiltshire0** [comment]
As he pointed out this domain, it is more likely that he wants to do it here

**Comment by opdev1004** [comment]
Actually now I get what he means.

He's pointing out the missing pages that is connected from document pages.

Because we don't have does pages, it will just show errors.

**Comment by tokengamedev** [comment]
Just to throw more light on the Issue:

**license:** You can create a page as specified in Godot, or not. IMO it is not required. Link should be removed from Docs
**community:** Yes, it is required given, Nicholai has shared more of Social sites in the discord, they should be in one place as public info
**contacts:** Yes, it is required. At this point it may not happen, but if Redot grows as big and famous as Godot, then there should be contacts on the website 

Additionally:

**Terms of Service:** has to be provided as game developers need to have a reference link inside their game or apps, if required to. It is kind of requirement if you have to deploy into stores, I believe. 
**Privacy Policy:**  Same as Terms of Service

Now I shared my 2 cents. It is up to the website developers to decide.

**Comment by opdev1004** [comment]
This will take some time. And they are not urgent issue in my opinion. Maybe few weeks and months.

**Comment by chrisrabe** [comment]
License page in #148

**Comment by chrisrabe** [comment]
Created PR for license page. Requires approval from Drew regarding the license statements

Preview (accessible via footer)
https://cc9ea579.redot-landing-page-develop.pages.dev/

**Comment by opdev1004** [comment]
#151  adds a contact page and it is merged.

**Comment by opdev1004** [comment]
#175 is adding all the pages, we are closing this.
