### ISSUE TITLE
Improve web security

### ISSUE THREAD

**Issue by chrisrabe** [Redot-Engine/redot-landing-page#139]
**Issue description:**
Security scores are pretty low for the redotengine landing page. Need to add some security modules to improve SEO scores.

<img width="866" alt="Screenshot 2024-10-24 at 7 44 04 AM" src="https://github.com/user-attachments/assets/d55bc471-7282-4f49-9bd1-8b585f6c7a4b">

**Comment by MichaelFisher1997** [comment]
https://securityheaders.com/?q=https%3A%2F%2Fwww.redotengine.org%2F&followRedirects=on

**Comment by opdev1004** [comment]
https://developers.cloudflare.com/pages/configuration/headers/
There we go!

**Comment by opdev1004** [comment]
#143

**Comment by opdev1004** [comment]
https://securityheaders.com/?q=https%3A%2F%2Fdev.redotengine.org%2F&followRedirects=on
