### ISSUE TITLE
Redot's `4.4-alpha.1`'s release news article url is incorrect

### ISSUE THREAD

**Issue by Spartan322** [Redot-Engine/redot-landing-page#158]
**Issue description:** Redot's `4.4-alpha.1`'s release news article's URL refers to it as release `release-4-4` instead of `release-4-4-alpha-1` 

**URL to the web page:** https://www.redotengine.org/news/release-4-4

`release-4-4` should have a redirect to `release-4-4-alpha-1` until 4.4 stable is released, once its released is should have a mention at the bottom speaking about how the article originally mistakenly pointed to the 4.4 alpha.1 release with a link to the 4.4 alpha.1 release

**Comment by opdev1004** [comment]
#169
