### ISSUE TITLE
Perhaps remove the twitter link?

### ISSUE THREAD

**Issue by mak448a** [Redot-Engine/redot-landing-page#162]
**Issue description:**
On the main page where it says "Get Involved," it links to the twitter account, which got hacked (see posts on the redot blog).
Should the twitter link be removed?
**URL to the web page (if already existing):**
https://www.redotengine.org/

**Comment by opdev1004** [comment]
We may change link. But we may get that account back so just waiting for now.

**Comment by chrisrabe** [comment]
Merged PR #168. Will be in the next round of prod release
