### ISSUE TITLE
Lack of templates mirrorlist version jsons

### ISSUE THREAD

**Issue by Spartan322** [Redot-Engine/redot-landing-page#165]
**Issue description:** Redot website lacks expected template mirrorlists at https://redotengine.org/mirrorlist/ like https://godotengine.org/mirrorlist/4.3.stable.json

We should have https://redotengine.org/mirrorlist/4.3.beta.2.json for https://github.com/Redot-Engine/redot-engine/releases/tag/redot-4.3-beta.2

Same with https://godotengine.org/mirrorlist/4.3.stable.mono.json

**Comment by opdev1004** [comment]
Do you need that from engine side?

**Comment by Spartan322** [comment]
Yes, it is required for users to be able to download the templates from within the engine.

**Comment by opdev1004** [comment]
is it same content as godot mirror list though?

**Comment by Spartan322** [comment]
It should be, I'm pretty sure the engine doesn't like a tpz as the template archive's file extension, but I'm hoping the template zip may work fine, we don't need to replicate the tux family mirror as of now.

**Comment by opdev1004** [comment]
I am a bit confused with naming though. Is it really 4.3.alpha.2.json? isn't it beta?

Another question, in our engine repo, they are .zip file. Is it okay to use zip file url?

**Comment by Spartan322** [comment]
That's my typo, yeah it should be beta.

And we can try the zip sure, I think it shouldn't matter if I'm reading the engine's source code right.

**Comment by opdev1004** [comment]
#170
