### ISSUE TITLE
Update mirrorlist to 4.3 Beta 3

### ISSUE THREAD

**Issue by Spartan322** [Redot-Engine/redot-landing-page#179]
**Issue description:** Redot website needs https://godotengine.org/mirrorlist/4.3.beta-3.json referencing https://github.com/Redot-Engine/redot-engine/releases/download/redot-4.3-beta.3/Redot_v4.3-beta.3_export_templates.tpz, should coincide with a news article for 4.3 Beta 3.

**Comment by opdev1004** [comment]
I think we better automate this instead of always making json file. Seems pretty feel unnecessarily creating these files. Or fetching github release from engine side.
