### ISSUE TITLE
Amerta Project Sample

### ISSUE THREAD

**Issue by ciptakelvin** [Redot-Engine/redot-landing-page#18]
If you need a sample game using redot. I am willing to provide screenshots. I would love for you to use it.
Steam Page : https://store.steampowered.com/app/2138360/Amerta/
Press Kit : bit.ly/AmertaPressKit

![Screenshot from 2024-10-14 20-04-48](https://github.com/user-attachments/assets/56a9dfac-9f8f-47e5-ba5b-bced55d7b6e2)
![Screenshot from 2024-10-12 05-29-29](https://github.com/user-attachments/assets/3a2c2991-bbba-4ad9-a92f-c2803221572d)
![Screenshot from 2024-10-12 05-32-22](https://github.com/user-attachments/assets/fcab28dd-b3be-4462-b5b8-75be3445a8b3)
![Main Capsule](https://github.com/user-attachments/assets/0c84bc77-b2df-47bc-b2ab-3764b577e4af)

**Comment by chrisrabe** [comment]
Closing. Addressed in PR https://github.com/Redot-Engine/redot-landing-page/pull/43
