### ISSUE TITLE
Add `versions.json` file

### ISSUE THREAD

**Issue by Spartan322** [Redot-Engine/redot-landing-page#181]
**Issue description:** Godot has https://godotengine.org/versions.json which enables their website to tell the engine when a new release has occurred, Redot tries to do the same but it will instead return a 404 as we do not have a `version.json`.

**URL to the web page (if already existing):** https://redotengine.org/versions.json

**Comment by opdev1004** [comment]
Can't game engine fetch version from github release?

https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28

Or we just always need to do same thing what godot engine does?

Just asking, because most of issue I see is whether we are not doing what godot engine does.

**Comment by Spartan322** [comment]
Checking the REST API could be done, but its a lot of work to get right, it would take a bit of time (and QA) to implement so in the least this can be a stopgap until we did something like that.
