### ISSUE TITLE
Download page | enhance with more download options. (mono)

### ISSUE THREAD

**Issue by MichaelFisher1997** [Redot-Engine/redot-landing-page#217]
A few people have complained that it's unclear where to download other versions like mono.
They have pointed out how godot does it:
https://godotengine.org/download/windows/
So they are asking for something like this.
our current version:
![image](https://github.com/user-attachments/assets/3d5f59b9-262c-43d5-8110-ce24fce66e4b)

We don't have to fully copy godots layout, but we should at least clarify where to go for mono options and add a mono download link.

**Comment by charlottewiltshire0** [comment]
I don't think there's any point in adding this button since there is already a 'More download options' button
