### ISSUE TITLE
Redirect is not working properly

### ISSUE THREAD

**Issue by axisd** [Redot-Engine/redot-landing-page#223]
**Issue description:**
after clicking on the link inside the engine opens webpage https://docs.redotengine.org/en/4.3/blah-blah.html, which is then redirected https://docs-4.3.redotengine.org/blah-blah.html that has DNS_PROBE_FINISHED_NXDOMAIN error
coz subdomain docs-4.* and 3.* do not exist

for example
Engine's doc RichTextLabel - click on "BBCode in RichTextLabel"
opens webpage https://docs.redotengine.org/en/4.3/tutorials/ui/bbcode_in_richtextlabel.html
which is then redirected https://docs-4.3.redotengine.org/tutorials/ui/bbcode_in_richtextlabel.html

**Comment by axisd** [comment]
I think this is a web server settings problem, but I didn't know where to write this...

**Comment by opdev1004** [comment]
There's document website repository probably you can open an issue there.
Still DNS part might be related to us.
But our lead and person who managing our server side seems like having a rest or on holiday. They have been hard working for Redot and gotta sort out their life stuffs.
I will share this to web people but I cannot guarantee this is going to be fixed quickly.

**Comment by opdev1004** [comment]
im closing this because it seems fixed and not really related to here

https://docs.redotengine.org/en/stable/tutorials/ui/bbcode_in_richtextlabel

**Comment by axisd** [comment]
But it's still not working properly

Engine's doc RichTextLabel - click on "BBCode in RichTextLabel"
opens webpage https://docs.redotengine.org/en/4.3/tutorials/ui/bbcode_in_richtextlabel.html
with strange content "Html test root. Will be replaced by refresh/redirect" and links to test/stable/latest/3.6 docs

![image](https://github.com/user-attachments/assets/4158c5a0-1c2c-4cb0-9494-15878e3c2f97)

**Comment by opdev1004** [comment]
Go open an issue in document repo please. So you can get a proper response.

You may get a late reply because of holiday season.

Most of web dev here does not know what's going on with document site.

And there are many experimental project is going on. So document site may get replaced as well.

Even this repo will be replaced with new website since one of web dev is working on it.

**Comment by axisd** [comment]
ok. ty
[https://github.com/Redot-Engine/redot-docs/issues/82](url)
