### ISSUE TITLE
Add news filter

### ISSUE THREAD

**Issue by chrisrabe** [Redot-Engine/redot-landing-page#51]
We need a tag filter so that it's easier to find articles in the future

**Comment by opdev1004** [comment]
Can we elaborate more about this?

Is this feature work just like a blog that you click on tag and list items with same tag?

Like showing list page with related tag.

**Comment by chrisrabe** [comment]
@opdev1004 these are the chips on top of the news articles.

Figma URL: https://www.figma.com/design/47xbUZkEOEkDg7OBEkL5H9/ReDot-Website?node-id=2509-774&t=xjmfJISHTNJn5Lzi-1

<img width="1010" alt="Screenshot 2024-10-16 at 5 44 37 AM" src="https://github.com/user-attachments/assets/744250e4-cf96-4bab-893c-e50fc80bc35d">

**Comment by opdev1004** [comment]
#79
