### ISSUE TITLE
Fix sorting

### ISSUE THREAD

**Issue by adikhoff** [Redot-Engine/redot-landing-page#62]

**Comment by adikhoff** [comment]
The order of news articles is wrong. There are currently two fields, date and index, that sort the articles. According to how those fields are filled, we would expect the following order:
1. welcome-to-our-site
2. and-then-there-were-many
3. the-journey
4. the-web-side-of-things
5. mascot-contest
6. release-4-4

Front page:
![Image](https://github.com/user-attachments/assets/e25f3ebc-aee6-4529-8665-c85a2edfc050)

News overview:
![Image](https://github.com/user-attachments/assets/f9811e83-f006-4670-b982-bfe1eb8e7461)

**Comment by opdev1004** [comment]
I checked the code and it is being sorted by published date order.

**Comment by adikhoff** [comment]
The problem is that several articles have the same date, which is why index was introduced. I've added that to the sort predicate, played around with it until the order was right (but didn't know what I was doing really). Now the order is scrambled again

**Comment by opdev1004** [comment]
Okay. Now I understand what's going on. The markdown content can be numbered.
And the number will be automatically removed for generating.
I made same markdown content system for my web framework and I know nuxt content do same.
Let's see if numbering markdown files fix the problem.

**Comment by opdev1004** [comment]
#79
