### ISSUE TITLE
Fix hero component to be responsive

### ISSUE THREAD

**Issue by opdev1004** [Redot-Engine/redot-landing-page#68]
![d54dh16h](https://github.com/user-attachments/assets/3c0133e8-583b-48f9-9598-28c24700049f)

This is not responsive in mobile.

**Comment by adikhoff** [comment]
Are there phones with 320x480 resolution?

**Comment by opdev1004** [comment]
Apparently that's the lowest resolution

**Comment by adikhoff** [comment]
The more you know...

**Comment by adikhoff** [comment]
Another question: Would people actually use their phone to download a game engine that would only run on a PC?

**Comment by opdev1004** [comment]
I guess we may not fix it. Because as you mentioned people wouldn't click the button anyway.

So I did more research and be more realistic. Apparently iPhone 3GS and iphone 4 is 320px 480px 😬
But luckily not much people have them and it's almost impossible to do any web search.

Then there's iphone 5 320px 568px  And there are some people still using it in this world. And it just totally works for web search.

![gh1f6g4](https://github.com/user-attachments/assets/bc894eb7-55dd-4914-a812-a03395c968c4)

Then it looks alright to me. So I am closing this issue.
