### ISSUE TITLE
create a github pages for backup site or/and testing

### ISSUE THREAD

**Issue by DeanLemans** [Redot-Engine/redot-landing-page#72]
create a github pages for backup site.

Could also be used for staging(alpha?) site for testing.

If this is not needed close this issue

**Comment by opdev1004** [comment]
Maybe not a wrong direction for back-up.

**Comment by chrisrabe** [comment]
We currently have a separate domain for develop builds so that it can be tested before being merged into the main site. Might not be necessary.

Stage URL: https://dev.redotengine.org/

**Comment by opdev1004** [comment]
looks like not going to happen so I am closing this.
