### ISSUE TITLE
Swap order of 2D square and 3D cube to match order of text.

### ISSUE THREAD

**Issue by kenneth-leblanc** [Redot-Engine/redot-landing-page#75]
Very minor issue, but here on the homepage you can see where it talks about the engine having a dedicated 2D and 3D engines.
![image](https://github.com/user-attachments/assets/e7cf3ed1-639e-4fde-a5d3-a021dab88893)

However, I believe the image should match the order of the text. So the square should be on the left and the cube on the right.
This will align the image with the title.

**Comment by opdev1004** [comment]
good point ahahaha maybe he's a left hander
