### ISSUE TITLE
Enhance User Experience for Home page download buttons

### ISSUE THREAD

**Issue by opdev1004** [Redot-Engine/redot-landing-page#77]
![fhghagdh](https://github.com/user-attachments/assets/e275584b-4b4a-4d47-b014-c942360edd31)

We have same button for same purpose in same place.

### Feedback from discord
- Replace the one in hero with something like 'Get started' 
- Use different color
- Make the button bigger
- Let the download in the menu go to the list of releases (general download page) and make the download button on the main page a "Download latest" button that leads directly to the latest version

**Comment by adikhoff** [comment]
Also make it blue

**Comment by chrisrabe** [comment]
Also including feedback from community:

![Image](https://github.com/user-attachments/assets/bfbeabd6-7b0b-4308-a521-85e81f7366ce)
![Image](https://github.com/user-attachments/assets/045b51c5-8abd-4e29-96ab-59f612df294b)
