### ISSUE TITLE
Background buggy (strutting) on mobile

### ISSUE THREAD

**Issue by holy-mother-I-am-drunk** [Redot-Engine/redot-landing-page#94]
On mobile, when scrolling from top slowly the background behind the redot logo stutters.

**Comment by chrisrabe** [comment]
What type of mobile device are you using so that I can try to reproduce?

**Comment by adikhoff** [comment]
This might have to do with the absolute positioning of the hero footer. Some mobile browsers have a toolbar at the bottom that disappears when scrolling down. That causes the hero footer to suddenly drop down as well.

**Comment by holy-mother-I-am-drunk** [comment]
> What type of mobile device are you using so that I can try to reproduce?

I'm using a Xiaomi note 12, Firefox nightly as a browser.
Android 14 if that helps.

It's more like the image is trying to adjust itself multiple times to set coordinates.

**Comment by adikhoff** [comment]
> Xiaomi note 12, Firefox nightly as a browser

That will make it hard to reproduce.

**Comment by holy-mother-I-am-drunk** [comment]
> That will make it hard to reproduce.

It's not that bad of a problem, just an observation, if it can be fixed then good.
If not, then nothing severe, I had my Fair share of websites that do that even on other phones, even the rolls Royce website does that 😅.
So it's just a minor issue

**Comment by chrisrabe** [comment]
Marking as won't fix for now and closing issue
